#!/usr/bin/env bash
# Project canonical procedure contracts into managed adapter surfaces.
set -euo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
SOURCE="${WV_CONFIG_DIR:-$HOME/.config/weave}/procedures"
REPO="$(pwd)"
AGENT="all"
COPILOT_LINES=()
CODEX_IDS=()
CLAUDE_SKILLS=()
# Marker line embedded in every generated SKILL.md. Its presence is the single
# signal distinguishing a Weave-managed skill (safe to refresh/remove) from a
# hand-written one (must never be overwritten or pruned).
CLAUDE_MARKER='<!-- WEAVE-MANAGED-SKILL: do not edit; regenerated by project-procedures.sh -->'

for arg in "$@"; do
    case "$arg" in
        --source=*) SOURCE="${arg#*=}" ;;
        --repo=*) REPO="${arg#*=}" ;;
        --agent=all|--agent=claude|--agent=codex|--agent=copilot) AGENT="${arg#*=}" ;;
        *) echo "Usage: $0 [--source=<dir>] [--repo=<dir>] [--agent=claude|codex|copilot|all]" >&2; exit 2 ;;
    esac
done

# Validate the full contract set BEFORE mutating any consumer surface, so an
# invalid procedure aborts the run instead of silently pruning projections.
GEN="$SELF_DIR/gen-procedures.sh"
[ -x "$GEN" ] || { echo "project-procedures: validator not found at $GEN; refusing to project unvalidated contracts" >&2; exit 1; }
"$GEN" --source="$SOURCE" --check >/dev/null

# Exact-token adapter membership (validated to claude|codex|copilot above), so
# a value like 'notcodex' never matches by substring.
adapter_has() { # adapters-value token
    local t
    while IFS= read -r t; do [ "$t" = "$2" ] && return 0; done < <(echo "$1" | tr -d '[]' | tr ',' '\n' | sed 's/[[:space:]]//g')
    return 1
}

# Sparse, narrowing-only visibility override: ids under [local] in the target
# repo's config are force-demoted to local (kept out of projected surfaces).
# Only a [local] section is honored, so widening (local -> shared) is impossible.
OVERRIDE_LOCAL=""
if [ -f "$REPO/.weave/procedures-visibility.conf" ]; then
    OVERRIDE_LOCAL=$(awk '
        /^\[local\]/ { inside=1; next }
        /^\[/ { inside=0 }
        inside { sub(/#.*/, ""); gsub(/[[:space:]]/, ""); if ($0 != "") print }
    ' "$REPO/.weave/procedures-visibility.conf")
fi

project_one() {
    local file="$1" id description fallback adapters claude_skill body tmp
    id=$(awk -F': *' '/^id:/{print $2; exit}' "$file")
    description=$(awk '
        /^description:/ { v=$0; sub(/^description:[[:space:]]*/, "", v); inside=1; next }
        inside {
            if ($0 ~ /^[a-z_]+:/ || $0 ~ /^---$/) { inside=0; next }
            line=$0; sub(/^[[:space:]]+/, "", line)
            v=(v=="" ? line : v" "line)
        }
        END { print v }
    ' "$file" | tr -d '"')
    fallback=$(awk -F': *' '/^fallback:/{print $2; exit}' "$file" | tr -d '"')
    adapters=$(awk -F': *' '/^adapters:/{print $2; exit}' "$file")
    claude_skill=$(awk -F': *' '/^claude_skill:/{print $2; exit}' "$file")
    # Visibility gate: only shared procedures project into consumer adapter surfaces.
    # Default is local (opt-in to shipping); narrowing override can demote shared -> local.
    local visibility status
    visibility=$(awk -F': *' '/^visibility:/{print $2; exit}' "$file")
    visibility=${visibility:-local}
    if [ "$visibility" = shared ] && printf '%s\n' "$OVERRIDE_LOCAL" | grep -qxF "$id"; then
        visibility=local
    fi
    [ "$visibility" = shared ] || return 0
    # Draft procedures are shared-in-intent but not yet populated; never project
    # a placeholder shell into a consumer surface. A prior shared->draft demotion
    # is pruned by the stale-removal passes (codex managed flag, claude marker).
    status=$(awk -F': *' '/^status:/{print $2; exit}' "$file")
    [ "${status:-ready}" = ready ] || return 0
    body=$(awk 'BEGIN{n=0} /^---$/{n++; next} n>=2{print}' "$file")
    local do_claude=false do_codex=false do_copilot=false
    if adapter_has "$adapters" claude && { [ "$AGENT" = "all" ] || [ "$AGENT" = "claude" ]; }; then do_claude=true; fi
    if adapter_has "$adapters" codex && { [ "$AGENT" = "all" ] || [ "$AGENT" = "codex" ]; }; then do_codex=true; fi
    if adapter_has "$adapters" copilot && { [ "$AGENT" = "all" ] || [ "$AGENT" = "copilot" ]; }; then do_copilot=true; fi

    # Collision preflight — decide BEFORE mutating any adapter surface for this
    # procedure, so a hand-authored artifact is never partially overwritten.
    local skill_dir="$REPO/.claude/skills/$claude_skill" skill_md
    skill_md="$skill_dir/SKILL.md"
    if [ "$do_claude" = true ] && [ -f "$skill_md" ] && ! grep -qF "$CLAUDE_MARKER" "$skill_md"; then
        echo "procedure $id: refusing to overwrite hand-written skill '$claude_skill'" >&2
        return 1
    fi
    if [ "$do_codex" = true ] && [ -f "$REPO/.codex/weave.json" ] \
        && [ "$(jq --arg id "$id" '[.procedures[]? | select(.id == $id and (.managed != true))] | length' "$REPO/.codex/weave.json")" != 0 ]; then
        echo "procedure $id: refusing to overwrite hand-authored Codex entry '$id'" >&2
        return 1
    fi

    if [ "$do_claude" = true ]; then
        local staging resource executable parent rollback copy_ok=true
        parent="$(dirname "$skill_dir")"
        mkdir -p "$parent"
        # Stage under the destination parent (same filesystem) so the final swap is
        # an atomic rename and the live projection survives a copy failure.
        staging=$(mktemp -d "$parent/.weave-staging.XXXXXX")
        printf '%s\n' '---' "name: $claude_skill" "description: $description" '---' '' "$CLAUDE_MARKER" '' "$body" > "$staging/SKILL.md"
        while IFS='|' read -r resource executable; do
            [ -n "$resource" ] || continue
            cp "$(dirname "$file")/$resource" "$staging/$(basename "$resource")" || { copy_ok=false; break; }
            if [ "$executable" = true ]; then chmod +x "$staging/$(basename "$resource")"; else chmod -x "$staging/$(basename "$resource")"; fi
        done < <(awk '
            function flush() { if (path != "") { print path "|" exe; path="" } }
            /^resources:/{inside=1; next}
            inside && /^[a-z_]+:/{flush(); inside=0}
            inside && /^[[:space:]]*-[[:space:]]*path:/{flush(); sub(/.*path:[[:space:]]*/, ""); path=$0; exe="false"}
            inside && /^[[:space:]]*executable:/{sub(/.*executable:[[:space:]]*/, ""); exe=$0}
            END{flush()}
        ' "$file")
        if [ "$copy_ok" != true ]; then rm -rf "$staging"; echo "procedure $id: resource copy failed" >&2; return 1; fi
        # Atomic-ish swap: rename the old managed dir aside, move the new one in,
        # then drop the old. The live dir is replaced by a single rename.
        rollback=""
        if [ -d "$skill_dir" ]; then rollback="$parent/.weave-old.$claude_skill.$$"; mv "$skill_dir" "$rollback"; fi
        if ! mv "$staging" "$skill_dir"; then
            [ -n "$rollback" ] && mv "$rollback" "$skill_dir"
            rm -rf "$staging"
            echo "procedure $id: failed to install staged Claude skill" >&2
            return 1
        fi
        if [ -n "$rollback" ]; then rm -rf "$rollback"; fi
        CLAUDE_SKILLS+=("$claude_skill")
    fi
    if [ "$do_codex" = true ]; then
        CODEX_IDS+=("$id")
        mkdir -p "$REPO/.codex"
        [ -f "$REPO/.codex/weave.json" ] || printf '%s\n' '{"schema":"weave.codex.v1"}' > "$REPO/.codex/weave.json"
        tmp=$(mktemp)
        jq --arg id "$id" --arg description "$description" --arg fallback "$fallback" \
            '.procedures = ((.procedures // []) | map(select(.id != $id)) + [{id:$id,description:$description,fallback:$fallback,managed:true}])' \
            "$REPO/.codex/weave.json" > "$tmp"
        mv "$tmp" "$REPO/.codex/weave.json"
    fi
    if [ "$do_copilot" = true ]; then
        COPILOT_LINES+=("- $id — $description: $fallback")
    fi
}

# Check every targeted ownership boundary before the first projection write.
# A collision in a later procedure must not leave earlier Claude/Codex updates
# applied while Copilot/stale cleanup never runs.
preflight_one() {
    local file="$1" id adapters claude_skill visibility status skill_md
    id=$(awk -F': *' '/^id:/{print $2; exit}' "$file")
    adapters=$(awk -F': *' '/^adapters:/{print $2; exit}' "$file")
    claude_skill=$(awk -F': *' '/^claude_skill:/{print $2; exit}' "$file")
    visibility=$(awk -F': *' '/^visibility:/{print $2; exit}' "$file"); visibility=${visibility:-local}
    if [ "$visibility" = shared ] && printf '%s\n' "$OVERRIDE_LOCAL" | grep -qxF "$id"; then visibility=local; fi
    [ "$visibility" = shared ] || return 0
    status=$(awk -F': *' '/^status:/{print $2; exit}' "$file"); [ "${status:-ready}" = ready ] || return 0
    if adapter_has "$adapters" claude && { [ "$AGENT" = all ] || [ "$AGENT" = claude ]; }; then
        skill_md="$REPO/.claude/skills/$claude_skill/SKILL.md"
        if [ -f "$skill_md" ] && ! grep -qF "$CLAUDE_MARKER" "$skill_md"; then
            echo "procedure $id: refusing to overwrite hand-written skill '$claude_skill'" >&2
            return 1
        fi
    fi
    if adapter_has "$adapters" codex && { [ "$AGENT" = all ] || [ "$AGENT" = codex ]; } \
        && [ -f "$REPO/.codex/weave.json" ] \
        && [ "$(jq --arg id "$id" '[.procedures[]? | select(.id == $id and (.managed != true))] | length' "$REPO/.codex/weave.json")" != 0 ]; then
        echo "procedure $id: refusing to overwrite hand-authored Codex entry '$id'" >&2
        return 1
    fi
}

write_copilot_projection() {
    { [ "$AGENT" = "all" ] || [ "$AGENT" = "copilot" ]; } || return 0
    mkdir -p "$REPO/.github"
    local copilot="$REPO/.github/copilot-instructions.md" block
    block=$(printf '%s\n' '<!-- BEGIN WEAVE PROCEDURES -->' "${COPILOT_LINES[@]}" '<!-- END WEAVE PROCEDURES -->')
    if [ ! -f "$copilot" ]; then
        printf '%s\n' "$block" > "$copilot"
    elif grep -q 'BEGIN WEAVE PROCEDURES' "$copilot"; then
        awk -v block="$block" '
            /BEGIN WEAVE PROCEDURES/ { print block; skip=1; next }
            /END WEAVE PROCEDURES/ && skip { skip=0; next }
            !skip { print }
        ' "$copilot" > "$copilot.tmp"
        mv "$copilot.tmp" "$copilot"
    else
        printf '\n%s\n' "$block" >> "$copilot"
    fi
}

# Prune Weave-managed Codex entries (managed:true) that are no longer in the
# active set — a procedure deleted, demoted to local, or flipped to draft.
# Manually-authored entries (no managed flag) are always preserved.
remove_stale_codex_procedures() {
    { [ "$AGENT" = "all" ] || [ "$AGENT" = "codex" ]; } || return 0
    [ -f "$REPO/.codex/weave.json" ] || return 0
    local active tmp
    active=$(printf '%s\n' "${CODEX_IDS[@]:-}" | jq -R . | jq -s 'map(select(. != ""))')
    tmp=$(mktemp)
    jq --argjson active "$active" \
        '.procedures = ((.procedures // []) | map(.id as $pid | select((.managed != true) or (($active | index($pid)) != null))))' \
        "$REPO/.codex/weave.json" > "$tmp"
    mv "$tmp" "$REPO/.codex/weave.json"
}

# Prune Weave-managed skills (marker-bearing) that are no longer in the active
# shared set — a procedure deleted, demoted to local, or flipped to draft. Skills
# without the marker are hand-written and never touched.
remove_stale_claude_procedures() {
    { [ "$AGENT" = "all" ] || [ "$AGENT" = "claude" ]; } || return 0
    [ -d "$REPO/.claude/skills" ] || return 0
    local dir name
    for dir in "$REPO/.claude/skills"/*/; do
        [ -f "$dir/SKILL.md" ] || continue
        grep -qF "$CLAUDE_MARKER" "$dir/SKILL.md" || continue
        name=$(basename "$dir")
        if ! printf '%s\n' "${CLAUDE_SKILLS[@]:-}" | grep -qxF "$name"; then
            rm -rf "$dir"
        fi
    done
}

shopt -s nullglob
for procedure in "$SOURCE"/*.md; do preflight_one "$procedure"; done
for procedure in "$SOURCE"/*.md; do project_one "$procedure"; done
remove_stale_codex_procedures
remove_stale_claude_procedures
write_copilot_projection
